Certification power board
PayDock/e-commerce-woo pull request #23
Opened 2024-08-15 15:27 UTC by jspteampaydock

2024-08-16 11:31 UTC, jpcostello requested changes

2024-08-16 11:31 UTC, jpcostello commented on assets/js/frontend/form.js
> -        window.widgetReloaded = true
@jspteampaydock These were fixes added. Please pull changes before creating a PR.

2024-08-19 06:50 UTC, jspteampaydock commented on assets/js/frontend/form.js
> -        window.widgetReloaded = true
Ok, thanks , no problem

2024-08-28 12:44 UTC, FabianaRBarros requested changes

2024-08-28 12:44 UTC, FabianaRBarros commented on includes/Services/ProcessPayment/ApmProcessor.php
> +		WC()->cart->calculate_totals();
I think this was part of a fix from Andrii. @andryes can you please confirm?

2024-08-28 12:44 UTC, FabianaRBarros commented on includes/Services/ProcessPayment/ApmProcessor.php
> +		WC()->cart->calculate_totals();
Same for all cases like this one, for example: `BankAccountProcessor`, `CardProcessor`, `BankAccountBlock`

2024-08-28 12:44 UTC, FabianaRBarros commented on includes/Services/ProcessPayment/CardProcessor.php
> -
Please re-add this as this is part of a bug fix

2024-08-28 12:44 UTC, FabianaRBarros commented on resources/js/frontend/index.js
> -    fillCCDataError: __('Please fill in the required credit card form fields', textDomain),
Please re-add this as this is part of a bug fix

2024-08-28 12:51 UTC, FabianaRBarros commented on includes/Services/ProcessPayment/CardProcessor.php
> -
Please re-add this as this is part of a bug fix

2024-08-28 12:51 UTC, FabianaRBarros commented on includes/Services/ProcessPayment/CardProcessor.php
> -
Please re-add this as this is part of a bug fix

2024-08-28 13:26 UTC, FabianaRBarros approved these changes

2024-08-28 13:36 UTC, andryes approved these changes

2024-08-28 13:44 UTC, andryes approved these changes

2024-08-28 13:52 UTC, merged