SDK-673 and SDK-674 | Wallets not charging the correct amount
PayDock/e-commerce-woo pull request #40
Opened 2024-08-21 10:12 UTC by FabianaRBarros

2024-08-21 10:34 UTC, jpcostello approved these changes

2024-08-21 11:54 UTC, andryes approved these changes

2024-08-22 11:19 UTC, jpcostello requested changes
We are not going to merge our updates to classic checkout as per contract discussion.

2024-09-05 10:24 UTC, FabianaRBarros commented
We are not going to merge our updates to classic checkout.

2024-09-05 10:24 UTC, closed without merging